on:
  push:
    branches:
      - main
  workflow_dispatch:

name: Deploy dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Set up key
        run: set -eu
      - run: mkdir "$HOME/.ssh"
      - run: echo "${{ secrets.key }}" > "$HOME/.ssh/key"
      - run: chmod 600 "$HOME/.ssh/key"
      
      - name: Sync files
        shell: bash
        env:
          USER: ${{ secrets.user }}
          HOST: ${{ secrets.host }}
          DIST: ${{ secrets.dist }}
        run: ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no $USER@$HOST "cd /home/powerit && touch test"
